[ 2023-10-09 23:29:37,859 ] 30 cnnClassifierLogger - INFO - yaml file: F:\iNeuron\DL Projects\Chicken Disease Classification\config\config.yaml loaded successfully
[ 2023-10-09 23:29:37,864 ] 30 cnnClassifierLogger - INFO - yaml file: F:\iNeuron\DL Projects\Chicken Disease Classification\params.yaml loaded successfully
[ 2023-10-09 23:29:37,871 ] 21 cnnClassifierLogger - INFO - >>>>>> stage Data Ingestion stage started <<<<<<
[ 2023-10-09 23:29:38,902 ] 26 cnnClassifierLogger - ERROR - HTTP Error 429: Too Many Requests
Traceback (most recent call last):
  File "F:\iNeuron\DL Projects\Chicken Disease Classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 23, in <module>
    obj.main()
  File "F:\iNeuron\DL Projects\Chicken Disease Classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion.download_file()
  File "F:\iNeuron\DL Projects\Chicken Disease Classification\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    filename, headers = request.urlretrieve(
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\pravin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
